# CMake generated Testfile for 
# Source directory: /Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching
# Build directory: /Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/stitching
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_stitching "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/bin/opencv_test_stitching" "--gtest_output=xml:opencv_test_stitching.xml")
set_tests_properties(opencv_test_stitching PROPERTIES  LABELS "Main;opencv_stitching;Accuracy" WORKING_DIRECTORY "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1282;ocv_add_test_from_target;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1073;ocv_add_accuracy_tests;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;11;ocv_define_module;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;0;")
add_test(opencv_perf_stitching "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/bin/opencv_perf_stitching" "--gtest_output=xml:opencv_perf_stitching.xml")
set_tests_properties(opencv_perf_stitching PROPERTIES  LABELS "Main;opencv_stitching;Performance" WORKING_DIRECTORY "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/test-reports/performance" _BACKTRACE_TRIPLES "/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1193;ocv_add_test_from_target;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1074;ocv_add_perf_tests;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;11;ocv_define_module;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;0;")
add_test(opencv_sanity_stitching "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/bin/opencv_perf_stitching" "--gtest_output=xml:opencv_perf_stitching.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_stitching PROPERTIES  LABELS "Main;opencv_stitching;Sanity" WORKING_DIRECTORY "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVUtils.cmake;1640;add_test;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1194;ocv_add_test_from_target;/Users/brian/.opencv_dir/opencv-4.2.0/cmake/OpenCVModule.cmake;1074;ocv_add_perf_tests;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;11;ocv_define_module;/Users/brian/.opencv_dir/opencv-4.2.0/modules/stitching/CMakeLists.txt;0;")
