# Install script for directory: /Users/brian/.opencv_dir/opencv-4.2.0/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ade-LICENSE" FILES "/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/3rdparty/ade/ade-0.1.1f/LICENSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/core/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/dnn/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/features2d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/flann/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/gapi/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/highgui/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/java/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/js/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/ml/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/photo/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/python/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/stitching/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/ts/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/video/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/videoio/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/world/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/aruco/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/ccalib/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cudev/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/cvv/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/datasets/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/dpm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/face/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/freetype/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/hdf/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/hfs/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/img_hash/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/matlab/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/optflow/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/ovis/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/plot/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/quality/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/rapid/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/reg/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/rgbd/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/saliency/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/sfm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/shape/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/stereo/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/structured_light/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/superres/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/text/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/tracking/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/videostab/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/viz/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/.firstpass/xphoto/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/core/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/flann/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/imgproc/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/java_bindings_generator/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/ml/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/phase_unwrapping/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/photo/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/plot/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/python_tests/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/quality/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/reg/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/surface_matching/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/xphoto/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/dnn/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/dnn_superres/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/features2d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/freetype/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/fuzzy/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/gapi/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/hfs/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/img_hash/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/imgcodecs/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/line_descriptor/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/saliency/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/text/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/videoio/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/calib3d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/datasets/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/highgui/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/objdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/rapid/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/rgbd/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/shape/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/structured_light/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/ts/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/video/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/videostab/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/xfeatures2d/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/ximgproc/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/xobjdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/aruco/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/bgsegm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/bioinspired/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/ccalib/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/dnn_objdetect/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/dpm/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/face/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/optflow/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/stitching/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/superres/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/tracking/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/java/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/python_bindings_generator/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/stereo/cmake_install.cmake")
  include("/Users/brian/.opencv_dir/opencv-4.2.0/build-debug/modules/python3/cmake_install.cmake")

endif()

